Repository yourweather/yourweather-android, pull requests merged in 2023-09, with the labels that each got.

#495 [fix] : 캘린더 상세보기 창 seekBar 글씨 비율코딩 수정
  app/src/main/res/layout/activity_calendar_modify_weather.xml
  app/src/main/res/layout/activity_calendar_plus_weather.xml
Labels: fix, Pull Request👊, 리유/유리⛄

#498 [hotfix] home / 토스트 백그라운드 이미지 사이즈 조정
  app/src/main/res/drawable/bg_home_toast.xml
Labels: hotfix⚠️, Pull Request👊, 카야/예린☁️

#499 [hotfix/#493] weatherinput / 각종 ui 비율코딩 재적용
  app/src/main/res/layout/fragment_home_weather_input.xml
Labels: hotfix⚠️, Pull Request👊, 카야/예린☁️

#501 [fix/#500] toast / bg 이미지 너비 재조정
  app/src/main/res/layout/toast_home.xml
  app/src/main/res/layout/toast_initial.xml
  build.gradle
Labels: fix, Pull Request👊, 카야/예린☁️

#504 [fix] : 캘린더 상세보기 창 아이콘 가운데 정렬
  app/src/main/res/layout/activity_calendar_modify_weather.xml
  app/src/main/res/layout/activity_calendar_plus_weather.xml
  app/src/main/res/layout/activity_calendar_weather_detail.xml
Labels: fix, Pull Request👊, 리유/유리⛄

#507 [style/] filename / 파일명 변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/BottomNaviActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/SplashActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/adapter/UnwrittenRVAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/adapter/WrittenRVAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetailActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarMonth.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewAlarmActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewEmptyActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewStatusbarActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewTimepickerFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeatherActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetailActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageAlarmActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageLogoutFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageMyInfoActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageNicknameChangeActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPagePrivacyPolicyActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPagePwChangeActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageUsePolicyActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdarw3Activity.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw2Activity.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdrawActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/FindPwActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/FindPwEmailActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/NicknameActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/ResetPwActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignInActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2Activity.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUpActivity.kt
  app/src/main/res/layout/activity_bnv.xml
  app/src/main/res/layout/activity_calendar_detail.xml
  app/src/main/res/layout/activity_calendar_detail_view_empty.xml
  app/src/main/res/layout/activity_calendar_detail_view_statusbar.xml
  app/src/main/res/layout/activity_calendardetailview_alarm.xml
  app/src/main/res/layout/activity_find_pw.xml
  app/src/main/res/layout/activity_find_pw_email.xml
  app/src/main/res/layout/activity_my_info.xml
  app/src/main/res/layout/activity_my_page_alarm.xml
  app/src/main/res/layout/activity_my_page_nickname_change.xml
  app/src/main/res/layout/activity_my_page_privacy_policy.xml
  app/src/main/res/layout/activity_my_page_pw_change.xml
  app/src/main/res/layout/activity_my_page_use_policy.xml
  app/src/main/res/layout/activity_my_page_withdraw.xml
  app/src/main/res/layout/activity_my_page_withdraw2.xml
  app/src/main/res/layout/activity_my_page_withdraw3.xml
  app/src/main/res/layout/activity_nickname.xml
  app/src/main/res/layout/activity_pw_reset.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_sign_up2.xml
  app/src/main/res/layout/fragment_calendar_detailview_timepicker.xml
  app/src/main/res/layout/fragment_calendar_modify_weather.xml
  app/src/main/res/layout/fragment_withdraw_page.xml
Labels: style, Pull Request👊, 카야/예린☁️

#511 [fix]회원탈퇴 뷰 수정
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw2Activity.kt
  app/src/main/java/com/umc/yourweather/util/AlertDialogTwoBtnNoneSubtItle.kt
  app/src/main/res/layout/activity_my_page_withdraw2.xml
  app/src/main/res/layout/alertdialog_twobtn_none_subtitle.xml
Labels: add, fix, refactor, Pull Request👊, 진/서진☀️
