Repository yourweather/yourweather-android, pull requests merged in 2023-11, with the labels that each got.

#528 [remove/#527] 캘린더 상세보기에서 필요없는 파일들 삭제(기존 작업자가 남겨두고 간 파일)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewEmptyActivity.kt
  app/src/main/res/layout/activity_calendar_detail_view1.xml
  app/src/main/res/layout/activity_calendar_detail_view2.xml
  app/src/main/res/layout/activity_calendar_detail_view3.xml
  app/src/main/res/layout/activity_calendar_detail_view_empty.xml
Labels: remove, Pull Request👊, 진/서진☀️

#529 [refactor#518] CalendarDate.kt / CalendarDate.kt 원래 버전으로 돌리기
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDate.kt
Labels: refactor, Pull Request👊, 진/서진☀️

#533 [fix/#522]캘린더에서 화살표 위치 픽스
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarTotalViewFragment.kt
  app/src/main/res/drawable/ic_calendar_arrow_left.xml
  app/src/main/res/drawable/ic_calendar_arrow_right.xml
  app/src/main/res/layout/fragment_calendar_total_view.xml
Labels: add, fix, refactor, Pull Request👊, 진/서진☀️

#535 [fix/#526] 바텀네비 애니메이션 제거
  app/src/main/res/layout/activity_bnv.xml
  app/src/main/res/layout/fragment_analysis.xml
  app/src/main/res/layout/fragment_bnv_home.xml
  app/src/main/res/layout/fragment_bnv_my_page.xml
  app/src/main/res/layout/fragment_bnv_report.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_initial_no_weather.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_written_detail_list_cloud.xml
  app/src/main/res/layout/fragment_written_detail_list_cloud_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_rain.xml
  app/src/main/res/layout/fragment_written_detail_list_rain_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_sun.xml
  app/src/main/res/layout/fragment_written_detail_list_sun_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_thunder.xml
  app/src/main/res/layout/fragment_written_detail_list_thunder_weekly.xml
Labels: fix, Pull Request👊, 카야/예린☁️

#537 [feat/#534] login email exception 처리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/sign/AlreadySignUpActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUpActivity.kt
  app/src/main/res/layout/activity_already_sign_up.xml
Labels: feat, fix, 진/서진☀️

#538 [hotfix/#534] : 다시 백... 이미 가입한 유저 검사 주석처리
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUpActivity.kt
Labels: hotfix⚠️

#539 [fix/#536] : 홈화면 비는 현상 해결
  app/src/main/java/com/umc/yourweather/presentation/BottomNaviActivity.kt
Labels: fix, 진/서진☀️

#541 [fix/#540] : 화면 상단 부분 material3 디자인 기반으로 상단바 TAB으로 수정
  app/src/main/java/com/umc/yourweather/presentation/analysis/UnwrittenDetailListActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageAlarmActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageMyInfoActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageNicknameChangeActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPagePwChangeActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/FindPwEmailActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/ResetPwActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2Activity.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUpActivity.kt
  app/src/main/res/drawable/ic_tap_arrow_left_blck_55_56.xml
  app/src/main/res/layout/activity_find_pw_email.xml
  app/src/main/res/layout/activity_my_info.xml
  app/src/main/res/layout/activity_my_page_alarm.xml
  app/src/main/res/layout/activity_my_page_nickname_change.xml
  app/src/main/res/layout/activity_my_page_pw_change.xml
  app/src/main/res/layout/activity_pw_reset.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_sign_up2.xml
  app/src/main/res/layout/activity_unwritten_detail_list.xml
  app/src/main/res/menu/memu_appbar_back.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request👊

#543 [fix/#542] : app_name 유어웨더로 변경
  app/src/main/res/values/strings.xml
Labels: fix, 리유/유리⛄
