Repository yourweather/yourweather-android, pull requests merged in 2023-08, with the labels that each got.

#135 [demo/#123]calendar 데모영상용 로직
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDate.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarMonth.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/testCalendarData.kt
Labels: feat, 진/서진☀️, demo

#136 [feat/#133] 비교분석뷰 / 감정 날씨 통계 디자인 수정
  app/src/main/java/com/umc/yourweather/data/BarColor.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt
  app/src/main/res/drawable/bg_blue_rec_rain.xml
  app/src/main/res/drawable/bg_darkblue_rec_round_thunder.xml
  app/src/main/res/drawable/bg_gray_rec_cloud.xml
  app/src/main/res/drawable/bg_yellow_rec_round_sun.xml
  app/src/main/res/layout/fragment_bar_statics_monthly.xml
Labels: feat, Pull Request👊, 리유/유리⛄

#140 [feat/#138] homeweatherinput / 날씨 아이콘 클릭 이벤트 기능 구현
  app/src/main/java/com/umc/yourweather/presentation/HomeWeatherInputFragment.kt
  app/src/main/res/anim/btn_weather_scale.xml
Labels: feat, Pull Request👊, 카야/예린☁️

#147 [fix/#146] home / 홈화면 toast메시지 생성 시점 오류 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/BottomNavi.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragmentInteractionListener.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/InitialNoWeatherFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_weather_input.xml
  app/src/main/res/layout/fragment_initial_no_weather.xml
Labels: fix, Pull Request👊, 카야/예린☁️

#145 [style/#143] 소셜로그인 크기 변경
  app/src/main/java/com/umc/yourweather/presentation/sign/Nickname.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt
  app/src/main/res/layout/activity_sign_in.xml
Labels: style, 진/서진☀️

#150 [feat/#47]캘린더에 오늘 날짜 표시 기능 추가
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDate.kt
  app/src/main/java/com/umc/yourweather/util/CalendarUtils.kt
Labels: feat, Pull Request👊, 진/서진☀️

#151 [feat/#144] 비교분석뷰 / 날씨 말풍선 구현
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt
  app/src/main/res/drawable/bg_gray_balloon.xml
  app/src/main/res/layout/fragment_bar_statics_monthly.xml
  app/src/main/res/layout/fragment_bar_statics_weekly.xml
Labels: feat, Pull Request👊, 리유/유리⛄

#157 [demo/#156]calendardetailview/캘린더 상세보기 로직 수정
  app/src/main/java/com/umc/yourweather/presentation/CalendarDetailView1.kt
  app/src/main/java/com/umc/yourweather/presentation/CalendarDetailView3.kt
Labels: 코이/혜진🌊, demo

#158 [demo] 8월 4일 100도 수정
  app/src/main/java/com/umc/yourweather/presentation/calendar/testCalendarData.kt
Labels: Pull Request👊, 진/서진☀️, demo

#160 add : 캘린더 상세보기 버튼 눌렀을 경우 뷰 구현 #159
  app/src/main/java/com/umc/yourweather/presentation/CalendarDetailviewModify1.kt
  app/src/main/java/com/umc/yourweather/presentation/CalendarDetailviewModify2.kt
  app/src/main/res/drawable/bg_calendardetailview_backdialog.xml
  app/src/main/res/drawable/bg_home_appshare.xml
  app/src/main/res/drawable/btn_home_appshare_share.xml
  app/src/main/res/drawable/ic_calendardetailview_alertdialog_line1.xml
  app/src/main/res/drawable/ic_calendardetailview_alertdialog_line2.png
  app/src/main/res/layout/activity_calendar_detailview_modify1.xml
  app/src/main/res/layout/activity_calendar_detailview_modify2.xml
  app/src/main/res/layout/alertdialog_calendar_detailview_modify.xml
Labels: add, 코이/혜진🌊

#164 [setting/#163]레트로핏 의존성 추가, base url 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SocialSignCheck.kt
  app/src/main/res/layout/activity_social_sign_check.xml
  settings.gradle
Labels: setting

#166 [remove/#165] bnv의 불필요한 파일 삭제
  app/src/main/java/com/umc/yourweather/presentation/BnvCalender.kt
  app/src/main/java/com/umc/yourweather/presentation/BnvHome.kt
  app/src/main/java/com/umc/yourweather/presentation/BnvMyPage.kt
  app/src/main/java/com/umc/yourweather/presentation/BnvReport.kt
  app/src/main/java/com/umc/yourweather/presentation/BottomNavi.kt
Labels: remove, Pull Request👊, 카야/예린☁️

#172 [feat/#170] 마이페이지 / 첫 화면 뷰 재구성
  app/src/main/java/com/umc/yourweather/presentation/BottomNavi.kt
  app/src/main/java/com/umc/yourweather/presentation/MyPageFragment.kt
  app/src/main/java/com/umc/yourweather/remote/request/ChangePasswordRequest.kt
  app/src/main/java/com/umc/yourweather/remote/request/MemoRequest.kt
  app/src/main/java/com/umc/yourweather/remote/request/MemoUpdateRequest.kt
  app/src/main/java/com/umc/yourweather/remote/request/SignupRequest.kt
  app/src/main/java/com/umc/yourweather/remote/response/BooleanResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetHomeResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetMemoResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetMemoUpdateResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetMissedInputResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetSpecificMemoResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetStatisticResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetUserResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetWeatherResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/HomeResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/MemoReportResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/MemoResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/MemoUpdateResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/MissedInputResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/SpecificMemoResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/StatisticResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/StringResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/UserResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/VoidResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/WeatherResponse.kt
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request👊, 카야/예린☁️

#175 [refactor/#174] 마이페이지 / 첫 번째 뷰 디자인 수정
  app/src/main/res/layout/fragment_my_page.xml
Labels: refactor, Pull Request👊, 카야/예린☁️

#176 [setting/#167] 서버 연결 세팅
  app/build.gradle
  app/src/main/java/com/umc/yourweather/data/entity/CalendarDateInfo.kt
  app/src/main/java/com/umc/yourweather/data/remote/request/ChangePasswordRequest.kt
  app/src/main/java/com/umc/yourweather/data/remote/request/MemoRequest.kt
  app/src/main/java/com/umc/yourweather/data/remote/request/MemoUpdateRequest.kt
  app/src/main/java/com/umc/yourweather/data/remote/request/SignupRequest.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/BaseResponse.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/HomeResponse.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/MemoReportResponse.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/MemoResponse.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/MemoUpdateResponse.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/MissedInputResponse.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/SpecificMemoResponse.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/StatisticResponse.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/UserResponse.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/WeatherResponse.kt
  app/src/main/java/com/umc/yourweather/data/service/EmailService.kt
  app/src/main/java/com/umc/yourweather/data/service/LoginService.kt
  app/src/main/java/com/umc/yourweather/data/service/MemoService.kt
  app/src/main/java/com/umc/yourweather/data/service/ReportService.kt
  app/src/main/java/com/umc/yourweather/data/service/UserService.kt
  app/src/main/java/com/umc/yourweather/data/service/WeatherService.kt
  app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarSelectAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarTotalViewFragment.kt
  app/src/main/java/com/umc/yourweather/remote/request/ChangePasswordRequest.kt
  app/src/main/java/com/umc/yourweather/remote/request/MemoRequest.kt
  app/src/main/java/com/umc/yourweather/remote/request/MemoUpdateRequest.kt
  app/src/main/java/com/umc/yourweather/remote/request/SignupRequest.kt
  app/src/main/java/com/umc/yourweather/remote/response/BooleanResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetHomeResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetMemoResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetMemoUpdateResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetMissedInputResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetSpecificMemoResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetStatisticResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetUserResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/GetWeatherResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/HomeResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/MemoReportResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/MemoResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/MemoUpdateResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/MissedInputResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/SpecificMemoResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/StatisticResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/StringResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/UserResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/VoidResponse.kt
  app/src/main/java/com/umc/yourweather/remote/response/WeatherResponse.kt
Labels: setting, Pull Request👊, 카야/예린☁️

#178 [setting] : data class 패키지 옮김
  app/src/main/java/com/umc/yourweather/data/entity/BarData.kt
  app/src/main/java/com/umc/yourweather/data/entity/ItemUnwritten.kt
  app/src/main/java/com/umc/yourweather/data/entity/ItemWritten.kt
  app/src/main/java/com/umc/yourweather/presentation/adapter/UnwrittenRVAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/adapter/WrittenRVAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/UnwrittenDetailListFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloud.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloudWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRain.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRainWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSunWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunder.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunderWeekly.kt
Labels: setting, Pull Request👊, 리유/유리⛄

#179 [feat/#161] 비교분석 뷰 내 달 넘김 기능 구현
  app/src/main/java/com/umc/yourweather/presentation/analysis/IconStaticsMonthlyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/IconStaticsWeeklyFragment.kt
  app/src/main/res/layout/fragment_icon_statics_monthly.xml
  app/src/main/res/layout/fragment_icon_statics_weekly.xml
Labels: feat, Pull Request👊, 리유/유리⛄

#181 [refactor/#180]내 정보 액티비티 완성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/MyPageFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/MyPageMyInfo.kt
  app/src/main/java/com/umc/yourweather/presentation/MyPageNicknameChange.kt
  app/src/main/java/com/umc/yourweather/presentation/MyPagePwChange.kt
  app/src/main/res/drawable/btn_myinfo.xml
  app/src/main/res/drawable/my_info_btn.xml
  app/src/main/res/layout/activity_my_info.xml
  app/src/main/res/layout/activity_my_page_nickname_change.xml
  app/src/main/res/layout/activity_my_page_pw_change.xml
  app/src/main/res/values/strings.xml
Labels: add, feat, Pull Request👊, 진/서진☀️

#195 [feat/#192]레트로핏 오프젝트
  app/src/main/java/com/umc/yourweather/di/RetrofitApi.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/GlobalApplication.kt
  app/src/main/java/com/umc/yourweather/util/PreferenceUtil.kt
Labels: add, feat, Pull Request👊, 진/서진☀️

#198 [refactor]api setting
  app/.gitignore
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/di/App.kt
Labels: refactor, Pull Request👊, 진/서진☀️

#201 [add] : 구글 소셜로그인 정보 파일 추가(ignored file)
  google-services.json
Labels: add, Pull Request👊, 진/서진☀️

#202 [remove]removed cached
  google-services.json
Labels: hotfix⚠️, Pull Request👊, 진/서진☀️

#206 [feat/#205] report service 항목 구현
  app/src/main/java/com/umc/yourweather/data/remote/response/MemoReportResponse.kt
  app/src/main/java/com/umc/yourweather/data/service/ReportService.kt
Labels: feat, Pull Request👊, 리유/유리⛄

#200 [feat/#194] 마이페이지 - 알림설정 뷰 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/BottomNavi.kt
  app/src/main/java/com/umc/yourweather/presentation/MyPageAlarm.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageAlarm.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageMyInfo.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageNicknameChange.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPagePwChange.kt
  app/src/main/res/layout/activity_my_info.xml
  app/src/main/res/layout/activity_my_page_alarm.xml
  app/src/main/res/layout/activity_my_page_nickname_change.xml
  app/src/main/res/layout/activity_my_page_pw_change.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feat, Pull Request👊, 리유/유리⛄

#210 [feat/#208] service / user,memo service 항목 구현
  app/src/main/java/com/umc/yourweather/data/service/MemoService.kt
  app/src/main/java/com/umc/yourweather/data/service/UserService.kt
Labels: feat, Pull Request👊, 카야/예린☁️

#209 [feat/#207]LoginService 생성
  app/src/main/java/com/umc/yourweather/data/remote/request/LoginRequset.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/TokenResponse.kt
  app/src/main/java/com/umc/yourweather/data/service/LoginService.kt
Labels: add, feat, Pull Request👊, 진/서진☀️

#211 [refactor/ #207] : 파일명 오타 수정 LoginRequset.kt->LoginRequest.kt
  app/src/main/java/com/umc/yourweather/data/remote/request/LoginRequest.kt
  app/src/main/java/com/umc/yourweather/data/service/LoginService.kt
Labels: feat, Pull Request👊, 진/서진☀️

#214 [feat/#213] service / email, weather service 항목 구현
  app/src/main/java/com/umc/yourweather/data/service/EmailService.kt
  app/src/main/java/com/umc/yourweather/data/service/WeatherService.kt
Labels: feat, Pull Request👊, 카야/예린☁️

#217 [refactor/] mypage_first / 뷰 및 기능 수정
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: refactor, 카야/예린☁️

#220 [feat/#219] 회원가입 로직 이메일, 비밀번호, 플랫폼 값 닉네임으로 넘겨주기
  app/src/main/java/com/umc/yourweather/data/remote/request/SignupRequest.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/Nickname.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUp.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt
Labels: feat, 리유/유리⛄

#226 [feat/#225] 회원가입_이메일 / api 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/di/RefreshTokenService.kt
  app/src/main/java/com/umc/yourweather/di/RetrofitImpl.kt
  app/src/main/java/com/umc/yourweather/di/TokenAuthenticator.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUp.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt
  app/src/main/res/xml/network_security_config.xml
Labels: feat, 카야/예린☁️

#224 [add/#223] [add] 비밀번호 찾기 로직 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/sign/FindPw.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/FindPwEmail.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/ResetPw.kt
  app/src/main/res/layout/activity_find_pw_email.xml
  app/src/main/res/layout/activity_pw_reset.xml
  app/src/main/res/values/strings.xml
Labels: add, 리유/유리⛄

#228 [setting/#193] 캘린더 상세보기/캘린더 상세보기 파일 패키지 이동
  app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailviewDiaryAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView1.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView3.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewEmpty.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify1.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendardetailviewAlarm.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/HorizontalScrollFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/HorizontalScrollFragment2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ModifyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ModifyFragment2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ScrollviewFragment1.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ScrollviewFragment2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/WritingNowFragment.kt
  app/src/main/res/layout/activity_calendardetailview_alarm.xml
  app/src/main/res/layout/card_calendar_detailview.xml
  app/src/main/res/layout/fragment_horizontal_scroll.xml
  app/src/main/res/layout/fragment_horizontal_scroll2.xml
  app/src/main/res/layout/fragment_modify.xml
  app/src/main/res/layout/fragment_modify2.xml
  app/src/main/res/layout/fragment_scrollview1.xml
  app/src/main/res/layout/fragment_scrollview2.xml
  app/src/main/res/layout/fragment_writing_now.xml
  app/src/main/res/values/ids.xml
Labels: setting, 코이/혜진🌊

#233 [refactor/#232] 비교분석뷰 지난 주/달 비교 데이터 텍스트 코드 구조 변경
  app/src/main/java/com/umc/yourweather/di/RetrofitImpl.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt
  app/src/main/res/layout/fragment_bar_statics_monthly.xml
  app/src/main/res/layout/fragment_bar_statics_weekly.xml
Labels: refactor, 리유/유리⛄

#236 [fix/#221] analysis view 뷰 세부 수정
  app/src/main/java/com/umc/yourweather/presentation/analysis/AllWrittenFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/IconStaticsMonthlyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/IconStaticsWeeklyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/UnwrittenDetailListFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloud.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloudWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRain.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRainWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSunWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunder.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunderWeekly.kt
  app/src/main/res/drawable/ic_gray_leftarrow_7_12.xml
  app/src/main/res/drawable/ic_gray_rightarrow_7_12.xml
  app/src/main/res/drawable/img_bell_event.xml
  app/src/main/res/layout/fragment_all_written.xml
  app/src/main/res/layout/fragment_analysis.xml
  app/src/main/res/layout/fragment_icon_statics_monthly.xml
  app/src/main/res/layout/fragment_icon_statics_weekly.xml
  app/src/main/res/layout/fragment_unwritten_detail_list.xml
  app/src/main/res/layout/fragment_written_detail_list_cloud.xml
  app/src/main/res/layout/fragment_written_detail_list_cloud_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_rain.xml
  app/src/main/res/layout/fragment_written_detail_list_rain_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_sun.xml
  app/src/main/res/layout/fragment_written_detail_list_sun_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_thunder.xml
  app/src/main/res/layout/fragment_written_detail_list_thunder_weekly.xml
Labels: fix, Pull Request👊, 리유/유리⛄

#235 [fix] : 캘린더 상세보기 코드 오류 수정 #234
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/CalendarDetailView1.kt
  app/src/main/java/com/umc/yourweather/presentation/CalendarDetailView2.kt
  app/src/main/java/com/umc/yourweather/presentation/CalendarDetailView3.kt
  app/src/main/java/com/umc/yourweather/presentation/CalendarDetailViewEmpty.kt
  app/src/main/java/com/umc/yourweather/presentation/CalendarDetailviewModify1.kt
  app/src/main/java/com/umc/yourweather/presentation/CalendarDetailviewModify2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarMonth.kt
  app/src/main/res/layout/activity_calendar_detail_view1.xml
  app/src/main/res/layout/activity_calendar_detail_view2.xml
  app/src/main/res/layout/activity_calendar_detail_view3.xml
  app/src/main/res/layout/activity_calendar_detail_view_empty.xml
  app/src/main/res/layout/activity_calendar_detailview_modify1.xml
  app/src/main/res/layout/activity_calendar_detailview_modify2.xml
Labels: fix, 코이/혜진🌊

#238 [feat/#229] signin api
  app/src/main/java/com/umc/yourweather/data/service/LoginService.kt
  app/src/main/java/com/umc/yourweather/di/RetrofitImpl.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
  app/src/main/res/layout/activity_sign_in.xml
Labels: feat, Pull Request👊, 진/서진☀️

#241 [refactor/#240]home,weatherinput / 뷰 및 기능 수정
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/InitialNoWeatherFragment.kt
  app/src/main/res/drawable/bg_home_weatherinput.xml
  app/src/main/res/drawable/ic_home_seekbarbtn.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_weather_input.xml
  app/src/main/res/values/dimes.xml
Labels: refactor, 카야/예린☁️

#243 [refactor/#229] : 로그인 후 홈화면 이동
  app/src/main/java/com/umc/yourweather/data/remote/response/TokenResponse.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
Labels: feat, refactor, Pull Request👊, 진/서진☀️

#247 [feat#249] 비교분석 bar 통계 부분 API 붙이기
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt
  app/src/main/res/layout/fragment_bar_statics_monthly.xml
  app/src/main/res/layout/fragment_bar_statics_weekly.xml
Labels: feat, Pull Request👊, 리유/유리⛄

#250 [refactor/#243]로그인 뷰 수정
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
  app/src/main/java/com/umc/yourweather/util/SignUtils.kt
  app/src/main/res/drawable/ic_selector_pwtoggle.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/toast_signin.xml
Labels: refactor, 진/서진☀️

#255 [feat/#251] 소셜 로그인 api 테스트 완
  app/src/main/java/com/umc/yourweather/data/service/LoginService.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
Labels: feat, Pull Request👊, 진/서진☀️

#256 [add/#254]캘린더 상세보기 / 캘린더 상세보기 저장 버튼 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify1.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ModifyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ModifyFragment2.kt
  app/src/main/res/layout/activity_calendar_detailview_modify1.xml
  app/src/main/res/layout/activity_calendar_detailview_modify2.xml
  app/src/main/res/layout/alertdialog_calendar_detailview_modify.xml
  app/src/main/res/values/ids.xml
Labels: add, 코이/혜진🌊

#253 [feat/#252] 증가, 감소, 동일에 따른 화살표 이미지 변경 기능
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt
  app/src/main/res/drawable/ic_certain.xml
  app/src/main/res/layout/fragment_bar_statics_monthly.xml
  app/src/main/res/layout/fragment_bar_statics_weekly.xml
Labels: feat, Pull Request👊, 리유/유리⛄

#259 [feat/#258] 비교분석뷰 각 날씨별 각 월 통계 받아오는 API 붙이기
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/IconStaticsMonthlyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/IconStaticsWeeklyFragment.kt
Labels: feat, Pull Request👊, 리유/유리⛄

#262 [hofix/#] : manifest file수정 #261
  app/src/main/AndroidManifest.xml
Labels: hotfix⚠️, 코이/혜진🌊

#260 [Feat#257]캘린더 상세보기/캘린더 상세보기 기록 시간 설정 창 구현
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendardetailviewAlarm.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feat, 코이/혜진🌊

#267 [feat/#266] detail list api 붙이기 비교분석뷰
  app/src/main/java/com/umc/yourweather/data/service/ReportService.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/IconStaticsMonthlyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/IconStaticsWeeklyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloud.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloudWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRain.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRainWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSunWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunder.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunderWeekly.kt
  app/src/main/res/layout/fragment_icon_statics_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_cloud.xml
  app/src/main/res/layout/fragment_written_detail_list_rain.xml
  app/src/main/res/layout/fragment_written_detail_list_sun.xml
  app/src/main/res/layout/fragment_written_detail_list_sun_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_thunder.xml
Labels: feat, Pull Request👊, 리유/유리⛄

#270 [fix / #269] 마이페이지, 알람창 오류 수정
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendardetailviewAlarm.kt
  app/src/main/res/layout/activity_calendardetailview_alarm.xml
  app/src/main/res/layout/activity_my_page_withdraw2.xml
  app/src/main/res/values/styles.xml
Labels: fix, 코이/혜진🌊

#268 [refactor/#246]토큰 레트로핏 셋팅...
  app/src/main/java/com/umc/yourweather/di/RetrofitImpl.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarTotalViewFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
Labels: feat, Pull Request👊, 진/서진☀️

#272 [feat/#244] 홈화면-날씨입력창 / api 및 기능 구현
  app/src/main/java/com/umc/yourweather/data/enums/Status.kt
  app/src/main/java/com/umc/yourweather/data/remote/request/MemoRequest.kt
  app/src/main/java/com/umc/yourweather/data/remote/request/MemoUpdateRequest.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/HomeResponse.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/MemoResponse.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/MemoUpdateResponse.kt
  app/src/main/java/com/umc/yourweather/di/RetrofitImpl.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/Nickname.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt
Labels: feat, 카야/예린☁️

#275 [refactor/#274] 비교분석 / status import 오류 수정
  app/src/main/java/com/umc/yourweather/data/service/ReportService.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloud.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRain.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunder.kt
Labels: refactor, 카야/예린☁️

#277 [fix/#276] 각 날씨 디테일 리스트 뷰 구조, 텍스트 사이즈 수정
  app/src/main/res/layout/fragment_written_detail_list_cloud.xml
  app/src/main/res/layout/fragment_written_detail_list_cloud_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_rain.xml
  app/src/main/res/layout/fragment_written_detail_list_rain_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_sun.xml
  app/src/main/res/layout/fragment_written_detail_list_sun_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_thunder.xml
  app/src/main/res/layout/fragment_written_detail_list_thunder_weekly.xml
Labels: fix, Pull Request👊, 리유/유리⛄

#279 [add/#278] 홈 화면/홈 화면 공유버튼 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView1.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify1.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeshareFragment.kt
  app/src/main/res/drawable/bg_appshare.xml
  app/src/main/res/drawable/bg_share.xml
  app/src/main/res/drawable/btn_share.xml
  app/src/main/res/drawable/ic_download.xml
  app/src/main/res/drawable/ic_homeshare_line1.xml
  app/src/main/res/drawable/ic_homeshare_line2.png
  app/src/main/res/drawable/ic_instagram.png
  app/src/main/res/layout/activity_calendardetailview_alarm.xml
  app/src/main/res/layout/alert_dialog_mypage_withdraw.xml
  app/src/main/res/layout/alertdialog_share.xml
  app/src/main/res/layout/fragment_homeshare.xml
Labels: add, 코이/혜진🌊

#281 [feat/#280] 자동로그인 추가
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
Labels: feat, Pull Request👊

#283 [feat#280] : 자동로그인
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
Labels: Pull Request👊, 진/서진☀️

#287 [hotfix/#286] : 플랫폼 네이밍 오류 수정
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt
Labels: hotfix⚠️, Pull Request👊, 리유/유리⛄

#284 [feat/#230]calendar api
  app/src/main/java/com/umc/yourweather/data/remote/response/MonthResponse.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/MonthWeatherResponse.kt
  app/src/main/java/com/umc/yourweather/data/service/WeatherService.kt
  app/src/main/java/com/umc/yourweather/di/MySharedPreferences.kt
  app/src/main/java/com/umc/yourweather/di/TokenSharedPreferences.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDate.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarMonth.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarTotalViewFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
Labels: feat, refactor, 진/서진☀️

#293 [feat/#292] 주 중 특정 날씨 리스트 요청 API 붙이기
  app/src/main/java/com/umc/yourweather/data/service/ReportService.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloudWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRainWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSunWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunderWeekly.kt
  app/src/main/res/layout/fragment_written_detail_list_cloud.xml
  app/src/main/res/layout/fragment_written_detail_list_cloud_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_rain.xml
  app/src/main/res/layout/fragment_written_detail_list_rain_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_sun.xml
  app/src/main/res/layout/fragment_written_detail_list_sun_weekly.xml
  app/src/main/res/layout/fragment_written_detail_list_thunder.xml
  app/src/main/res/layout/fragment_written_detail_list_thunder_weekly.xml
Labels: feat, 리유/유리⛄

#295 [retactor/#291] : 레트로핏..
  app/src/main/java/com/umc/yourweather/di/RetrofitImpl.kt
Labels: feat, hotfix⚠️, Pull Request👊, 진/서진☀️

#294 [fix/#289] 회원가입 / 기능 수정
  app/src/main/java/com/umc/yourweather/presentation/sign/Nickname.kt
  app/src/main/res/layout/activity_nickname.xml
Labels: fix, 카야/예린☁️

#298 [retactor/#297] BaseResponse<String> -> BaseResponse<TokenResponse>
  app/src/main/java/com/umc/yourweather/data/service/UserService.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/Nickname.kt
Labels: refactor, 진/서진☀️

#305 [hotfix/#304] : SH 파일 이름 변경으로 인한 이슈 수정
  app/src/main/java/com/umc/yourweather/di/UserSharedPreferences.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageLogoutFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPagePwChange.kt
Labels: hotfix⚠️, Pull Request👊, 리유/유리⛄

#301 [fix/#300] 카카오 이슈 고치기 시도............
  app/build.gradle
Labels: fix, 진/서진☀️

#310 [feat/#309]비밀번호 재설정 api
  app/src/main/java/com/umc/yourweather/presentation/sign/ResetPw.kt
  app/src/main/java/com/umc/yourweather/util/SignUtils.kt
Labels: feat, 진/서진☀️

#311 [feat/#308] 홈-날씨입력창 / 기능 추가 및 뷰 수정
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/InitialNoWeatherFragment.kt
  app/src/main/res/drawable/bg_home1_cloudy.jpg
  app/src/main/res/drawable/bg_home1_lightning.jpg
  app/src/main/res/drawable/bg_home1_rainy.jpg
  app/src/main/res/drawable/bg_home1_sunny.jpg
  app/src/main/res/drawable/bg_home2_lightningcloudy.jpg
  app/src/main/res/drawable/bg_home2_rainycloudy.jpg
  app/src/main/res/drawable/bg_home2_rainylightning.jpg
  app/src/main/res/drawable/bg_home2_sunnycloudy.jpg
  app/src/main/res/drawable/bg_home2_sunnylightning.jpg
  app/src/main/res/drawable/bg_home2_sunnyrainy.jpg
  app/src/main/res/drawable/bg_home3_cloudyrainylightning.jpg
  app/src/main/res/drawable/bg_home3_sunnycloudylightning.jpg
  app/src/main/res/drawable/bg_home3_sunnycloudyrainy.jpg
  app/src/main/res/drawable/bg_home3_sunnyrainylightning.jpg
  app/src/main/res/drawable/bg_seekbar_value.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_weather_input.xml
  app/src/main/res/layout/fragment_initial_no_weather.xml
Labels: feat, 카야/예린☁️

#318 [add/#312] 마이페이지 / 마이페이지 이벤트 기록 설정 뷰 구현
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPagePlus.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPagePlusAlarm.kt
  app/src/main/res/layout/activity_my_page_plus.xml
  app/src/main/res/layout/activity_my_page_plus_alarm.xml
  app/src/main/res/layout/alertdialog_my_page_plus_delete.xml
Labels: add, 코이/혜진🌊

#314 [feat/#313]회원탈퇴 api
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageMyInfo.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdarw3.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw2.kt
  app/src/main/java/com/umc/yourweather/util/AlertDialogTwoBtn.kt
  app/src/main/res/layout/activity_my_page_withdraw2.xml
  app/src/main/res/layout/activity_my_page_withdraw3.xml
  app/src/main/res/layout/alertdialog_twobtn.xml
  app/src/main/res/values/strings.xml
Labels: add, feat, refactor, Pull Request👊, 진/서진☀️

#320 [refactor/#319] 마이페이지 / first 뷰 수정
  app/src/main/res/layout/activity_my_info.xml
  app/src/main/res/layout/activity_my_page_plus.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: refactor, Pull Request👊, 카야/예린☁️

#322 [feat/#273] home / 배경전환 기능 구현
  app/src/main/java/com/umc/yourweather/data/remote/response/HomeResponse.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragment.kt
  app/src/main/res/drawable/bg_seekbar_value.xml
  app/src/main/res/layout/fragment_home_weather_input.xml
Labels: feat, Pull Request👊, 카야/예린☁️

#321 [feat/#319]calendar to calendar detail
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarMonth.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/testCalendarData.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw2.kt
Labels: feat, 진/서진☀️

#328 [feat/#326] 마이페이지 / 정책 api 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/data/service/PolicyService.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPagePrivacyPolicy.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageUsePolicy.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt
  app/src/main/res/drawable/bg_weather_guide.xml
  app/src/main/res/drawable/btn_weatherinput_guide.xml
  app/src/main/res/drawable/img_temp_guide.png
  app/src/main/res/drawable/img_weather_guide.png
  app/src/main/res/layout/activity_my_page_privacy_policy.xml
  app/src/main/res/layout/activity_my_page_use_policy.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_weather_input.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feat, Pull Request👊, 카야/예린☁️

#330 [fix/#306] 비교분석 뷰 API 수정
  app/src/main/java/com/umc/yourweather/data/entity/ItemWritten.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/SpecificMemoResponse.kt
  app/src/main/java/com/umc/yourweather/data/remote/response/StatisticResponse.kt
  app/src/main/java/com/umc/yourweather/presentation/adapter/WrittenRVAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/AnalysisFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloud.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloudWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRain.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRainWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSunWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunder.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunderWeekly.kt
  app/src/main/res/drawable/ic_certain.xml
  app/src/main/res/drawable/ic_downarrow.xml
  app/src/main/res/drawable/ic_uparrow.xml
  app/src/main/res/values/dimes.xml
Labels: fix, 리유/유리⛄

#331 [Feat/#329]회원가입시 바로 홈화면으로
  app/src/main/java/com/umc/yourweather/presentation/BottomNavi.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarTotalViewFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/Nickname.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/InitialNoWeatherFragment.kt
Labels: feat, Pull Request👊, 진/서진☀️

#335 [feat/#323] 날씨입력창 / alertdialog 추가
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt
  app/src/main/res/layout/alertdialog_weather_input_delete.xml
  app/src/main/res/layout/fragment_home.xml
Labels: feat, Pull Request👊, 카야/예린☁️

#339 [add/#338]회원가입시 안내 문구
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUp.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt
  app/src/main/java/com/umc/yourweather/util/SignUtils.kt
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_sign_up2.xml
Labels: add, 진/서진☀️

#345 [fix/] home / 기능 오류 수정
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt
Labels: fix, Pull Request👊, 카야/예린☁️

#350 [fix/#349] 날씨별 bar 색상 변경
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt
Labels: fix, Pull Request👊, 리유/유리⛄

#352 [add/#351] 캘린더 상세보기 / 파일 추가
  app/src/main/java/com/umc/yourweather/data/remote/response/MemoDailyResponse.kt
  app/src/main/java/com/umc/yourweather/data/service/MemoService.kt
  app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailviewDiaryAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView1.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView3.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewEmpty.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify1.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/HorizontalScrollFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/HorizontalScrollFragment2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ModifyFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ModifyFragment2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ScrollviewFragment1.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ScrollviewFragment2.kt
  app/src/main/res/layout/activity_calendar_detail_view1.xml
  app/src/main/res/layout/activity_calendar_detail_view2.xml
  app/src/main/res/layout/activity_calendar_detail_view3.xml
  app/src/main/res/layout/activity_calendar_detailview_modify1.xml
  app/src/main/res/layout/activity_calendar_detailview_modify2.xml
  app/src/main/res/layout/alert_dialog_alarm.xml
  app/src/main/res/layout/alertdialog_calendar_detailview_modify.xml
  app/src/main/res/layout/fragment_horizontal_scroll.xml
  app/src/main/res/layout/fragment_horizontal_scroll2.xml
  app/src/main/res/layout/fragment_modify.xml
  app/src/main/res/layout/fragment_modify2.xml
  app/src/main/res/layout/fragment_scrollview1.xml
  app/src/main/res/layout/fragment_scrollview2.xml
  app/src/main/res/layout/fragment_writing_now.xml
Labels: add, 카야/예린☁️

#353 [fix#/null] Service 잘못된거 수정
  app/src/main/java/com/umc/yourweather/data/remote/response/MemoDailyResponse.kt
  app/src/main/java/com/umc/yourweather/data/service/MemoService.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarMonth.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView1.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView3.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/HorizontalScrollFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/HorizontalScrollFragment2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ScrollviewFragment1.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ScrollviewFragment2.kt
Labels: fix, hotfix⚠️, 진/서진☀️

#355 [feat/#354] : 미입력 내역 날짜 CalendarDetailviewModify2로 전달
  app/src/main/java/com/umc/yourweather/presentation/adapter/UnwrittenRVAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/UnwrittenDetailListFragment.kt
Labels: feat, Pull Request👊, 리유/유리⛄

#357 [feat/#356] : 상세 입력 memoId CalendarDetailviewModify1로 전달
  app/src/main/java/com/umc/yourweather/presentation/adapter/WrittenRVAdapter.kt
Labels: feat, Pull Request👊, 리유/유리⛄

#359 [rafactor/#358]자잘한 view 수정
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw2.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUp.kt
  app/src/main/res/layout/fragment_calendar_total_view.xml
Labels: feat, fix, 진/서진☀️

#360 [refactor/#336] : 비교분석 코루틴 적용
  app/src/main/java/com/umc/yourweather/presentation/BottomNavi.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/AnalysisFragment.kt
Labels: feat, Pull Request👊, 진/서진☀️

#363 [fix/#362] : 캘린더 상세보기 창 코드 수정
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView1.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView3.kt
  app/src/main/res/layout/activity_calendar_detail_view1.xml
  app/src/main/res/layout/activity_calendar_detail_view2.xml
  app/src/main/res/layout/activity_calendar_detail_view3.xml
  app/src/main/res/layout/card_calendar_detailview.xml
  app/src/main/res/layout/fragment_horizontal_scroll.xml
Labels: fix, 코이/혜진🌊

#364 [add/#336]회원탈퇴 버튼
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw2.kt
  app/src/main/res/drawable/btn_selector_withdraw.xml
  app/src/main/res/drawable/btn_withdraw_enabled_false.xml
  app/src/main/res/drawable/btn_withdraw_enabled_true.xml
  app/src/main/res/layout/activity_my_page_withdraw2.xml
Labels: add, Pull Request👊, 진/서진☀️

#377 [fix,feat/#376] 홈, 공유 / 오류 수정 및 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/share/CarmeraPermissionFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/share/SaveHomeImgFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeshareFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/InitialNoWeatherFragment.kt
  app/src/main/res/drawable/bg_carmera_permission.xml
  app/src/main/res/drawable/img_carmera_permission.png
  app/src/main/res/layout/fragment_carmera_permission.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_homeshare.xml
  app/src/main/res/layout/fragment_save_home_img.xml
Labels: feat, fix, Pull Request👊, 카야/예린☁️

#375 [feat] 상세보기 그래프 점찍기
  app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailMemoListAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt
  app/src/main/res/drawable/line_calendar_detail_graph.xml
  app/src/main/res/layout/activity_calendar_detail.xml
  app/src/main/res/layout/item_calendar_detail_memolist.xml
Labels: feat, Pull Request👊, 진/서진☀️

#379 [fix/#378] home / 강제종료 오류 수정
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt
  app/src/main/res/layout/fragment_home_weather_input.xml
Labels: fix, 카야/예린☁️

#384 [fix] home / 캡쳐 및 갤러리 저장 기능 수정
  app/src/main/java/com/umc/yourweather/presentation/share/SaveHomeImgFragment.kt
Labels: fix, Pull Request👊, 카야/예린☁️

#382 [add/#373] : timepicker뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewTimepicker.kt
  app/src/main/res/layout/fragment_calendar_detailview_timepicker.xml
Labels: add, 코이/혜진🌊

#386 [feat/#385] modify1 기능구현
  app/src/main/java/com/umc/yourweather/data/remote/response/MemoResponse.kt
  app/src/main/java/com/umc/yourweather/data/service/MemoService.kt
  app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailMemoListAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify1.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/TimePickerFragment.kt
  app/src/main/res/layout/activity_calendar_detailview_modify1.xml
Labels: feat, Pull Request👊, 리유/유리⛄

#387 [remove/#369] 차트 주석처리
  app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailMemoListAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt
  app/src/main/res/layout/activity_calendar_detail.xml
  app/src/main/res/layout/item_calendar_detail_memolist.xml
Labels: remove, Pull Request👊, 진/서진☀️

#389 [fix/#388] modify1 view
  app/src/main/java/com/umc/yourweather/presentation/adapter/WrittenRVAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloud.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloudWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRain.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRainWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSunWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunder.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunderWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify1.kt
  app/src/main/res/layout/activity_calendar_detailview_modify1.xml
  app/src/main/res/layout/activity_calendar_detailview_modify2.xml
Labels: fix, Pull Request👊, 리유/유리⛄

#398 [feat/ #396] : timepicker/timepicker 기능 구현
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify2.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewTimepicker.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/TimePickerCallback.kt
Labels: feat, 코이/혜진🌊

#397 [remove/#393] 상세보기 일기가 없는 경우
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailMemoListAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/adapter/UnwrittenRVAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/adapter/WrittenRVAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewEmpty.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewTimepicker.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarModifyWeatherFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt
  app/src/main/res/layout/activity_calendar_detail.xml
  app/src/main/res/layout/activity_calendar_plus_weather.xml
  app/src/main/res/layout/activity_calendar_weather_detail.xml
  app/src/main/res/layout/fragment_calendar_modify_weather.xml
Labels: remove, Pull Request👊, 리유/유리⛄

#399 [feat/#369] 캘린더 점찍은 버전
  app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailMemoListAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt
  app/src/main/res/layout/activity_calendar_detail.xml
  app/src/main/res/layout/item_calendar_detail_memolist.xml
Labels: Pull Request👊, 진/서진☀️

#402 [feat/#369] 수정 완 그래프추가 남음
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt
  app/src/main/res/drawable/bg_gray_ed_fill_5_rect.xml
  app/src/main/res/layout/activity_calendar_detail.xml
Labels: feat, Pull Request👊, 진/서진☀️

#400 [feat/#396] : timepicker기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewTimepicker.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/TimePickerCallback.kt
  build.gradle
Labels: feat, 코이/혜진🌊

#403 [feat/}detaill modify 뷰 생성 + 머지 후 충돌 오류 수정
  app/build.gradle
  app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailMemoListAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt
  app/src/main/res/layout/fragment_calendar_modify_weather.xml
Labels: fix, 리유/유리⛄

#405 [feat/#390] 상세보기 편집 프래그먼트, 메모 수정 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/data/remote/response/MemoUpdateResponse.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarModifyWeatherActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarModifyWeatherFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt
  app/src/main/res/layout/activity_calendar_modify_weather.xml
Labels: feat, Pull Request👊, 리유/유리⛄

#408 [refactor/#407] weatherinput / 날씨입력창 및 기타 뷰 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewAlarm.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewTimepicker.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarModifyWeatherFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt
  app/src/main/res/drawable/bg_seekbar_value.xml
  app/src/main/res/drawable/img_carmera_permission.png
  app/src/main/res/drawable/img_carmera_permission.xml
  app/src/main/res/layout/activity_calendardetailview_alarm.xml
  app/src/main/res/layout/activity_sign_up2.xml
  app/src/main/res/layout/fragment_calendar_detailview_timepicker.xml
  app/src/main/res/layout/fragment_horizontal_scroll.xml
  app/src/main/res/layout/fragment_horizontal_scroll2.xml
  app/src/main/res/layout/fragment_scrollview1.xml
  app/src/main/res/layout/fragment_scrollview2.xml
  app/src/main/res/layout/fragment_writing_now.xml
  app/src/main/res/values-night/themes.xml
Labels: refactor, 카야/예린☁️

#411 [fix/#] 앱 빌드시 2개 생성되는 오류 해결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/share/SaveHomeImgFragment.kt
  app/src/main/res/layout/fragment_home_weather_input.xml
Labels: fix, 카야/예린☁️

#412 [feat/#391] 상세보기에서 메모 삭제 기능 추가
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt
  app/src/main/res/layout/activity_calendar_weather_detail.xml
Labels: feat, Pull Request👊, 리유/유리⛄

#415 [add/#414] : 캘린더 상세보기 상단바 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewStatusbar.kt
  app/src/main/res/layout/activity_calendar_detail_view_statusbar.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: add, 코이/혜진🌊

#417 [feat/#416] 타임피커 값을 메모 저장 API의 날짜값으로 보내기
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewTimepicker.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/TimePickerFragment.kt
  app/src/main/res/layout/activity_calendar_detail.xml
Labels: feat, Pull Request👊, 리유/유리⛄

#419 [feat/#418] 맡은 api 부분 요청 오류시 로그인 화면으로 이동하게
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw2.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/FindPw.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/FindPwEmail.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
Labels: feat, 진/서진☀️

#420 [fix/#413] 편집 창 넘어갈 때 해당 메모의 값도 가지고 넘어가서 보여주기
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarModifyWeatherActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt
Labels: fix, Pull Request👊, 리유/유리⛄

#422 [fix/ #421] : 변경된 닉네임으로 SH로 저장
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageNicknameChange.kt
Labels: fix, 리유/유리⛄

#424 [feat/#423] : 캘린더 상세보기 상단바 추가
  app/src/main/res/drawable/btn_calendardetailview_back.xml
  app/src/main/res/layout/activity_calendar_detail.xml
  app/src/main/res/layout/activity_calendar_detail_view_statusbar.xml
Labels: feat, 코이/혜진🌊

#426 [fix#425] finish로 끝나서 기존 화면으로 돌아온 경우 뷰 갱신
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt
Labels: fix, 리유/유리⛄

#428 [fix/#427]calendar total view
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDate.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarMonth.kt
Labels: feat, fix, Pull Request👊, 진/서진☀️

#431 [style/#430] 불필요 기능 주석처리
  app/src/main/java/com/umc/yourweather/presentation/share/SaveHomeImgFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: style, 카야/예린☁️

#433 [demo/#404] : 토클 버튼 ON 상태 시 알림 울림, 토글 버튼 상태 SH 저장
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageAlarm.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: feat, Pull Request👊, 리유/유리⛄

#435 [feat/#434] initial / 닉네임 관련 api 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/InitialNoWeatherFragment.kt
  app/src/main/res/layout/fragment_initial_no_weather.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feat, Pull Request👊, 카야/예린☁️

#437 [hotfix/#436] : 알림 설정 뷰 누락 부분 수정
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: hotfix⚠️, Pull Request👊, 리유/유리⛄

#439 [hotfix/#438] : 알림 내용에 유저 닉네임 추가
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageAlarm.kt
Labels: hotfix⚠️, Pull Request👊, 리유/유리⛄

#441 [fix/#440] 미입력내역, 비교분석 표 잘림 부분 해결
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt
  app/src/main/res/layout/fragment_icon_statics_monthly.xml
  app/src/main/res/layout/fragment_icon_statics_weekly.xml
  app/src/main/res/layout/fragment_unwritten_detail_list.xml
Labels: fix, Pull Request👊, 리유/유리⛄

#448 [fix/#447] v
  app/src/main/java/com/umc/yourweather/data/remote/request/MemoRequest.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt
Labels: fix, Pull Request👊, 리유/유리⛄

#446 [fix/#445] 캘린더 상세보기 창 뷰 수정
  app/src/main/res/drawable/btn_calendarview_delete.xml
  app/src/main/res/layout/activity_calendar_modify_weather.xml
  app/src/main/res/layout/activity_calendar_plus_weather.xml
  app/src/main/res/layout/activity_calendar_weather_detail.xml
  app/src/main/res/layout/activity_my_info.xml
Labels: fix, 리유/유리⛄

#452 [fix/#449] home / 광고 뷰 오류 해결 및 너비 수정
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: fix, 카야/예린☁️

#455 [feat/#453] SeekBar에서 감정 상세 온도 알려주는 텍스트 박스
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarModifyWeatherActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt
  app/src/main/res/layout/activity_calendar_modify_weather.xml
  app/src/main/res/layout/activity_calendar_plus_weather.xml
  app/src/main/res/layout/activity_calendar_weather_detail.xml
Labels: feat, 리유/유리⛄

#457 [feat/#456] : 캘린더 기록입력, 수정 부분 입력 취소 시 다이얼로그 창
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarModifyWeatherActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt
Labels: feat, Pull Request👊, 리유/유리⛄

#458 [feat/#450] alertdialog / 서브타이틀 추가
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt
  app/src/main/java/com/umc/yourweather/util/AlertDialogTwoBtn.kt
  app/src/main/res/layout/alertdialog_twobtn.xml
Labels: feat, Pull Request👊, 카야/예린☁️

#463 [refacotr/#454] home / 인스타 공유 기능 제외
  app/src/main/java/com/umc/yourweather/presentation/share/SaveHomeImgFragment.kt
  app/src/main/res/drawable/bg_share.xml
  app/src/main/res/layout/fragment_save_home_img.xml
Labels: refactor, 카야/예린☁️

#464 [Fix/#394] 저장한 경우 다이얼로그 안 뜨게, 서브 타이틀 문구 추가
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarModifyWeatherActivity.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt
Labels: fix, 리유/유리⛄

#466 [refactor/#465] initial / 닉네임 글자 수 상관없이 가운데 정렬 되게 위치 조정
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/InitialNoWeatherFragment.kt
  app/src/main/res/layout/fragment_initial_no_weather.xml
Labels: refactor, 카야/예린☁️

#469 [fix/#468] mypagenicknamechange / 글자 수 제한 기능 추가
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageNicknameChange.kt
  app/src/main/res/drawable/bg_share_img.xml
  app/src/main/res/layout/fragment_save_home_img.xml
Labels: fix, Pull Request👊, 카야/예린☁️

#470 [fix/#467]sign view
  app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailMemoListAdapter.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/FindPw.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/ResetPw.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt
  app/src/main/res/layout/activity_calendar_detail.xml
  app/src/main/res/layout/activity_find_pw.xml
  app/src/main/res/layout/activity_find_pw_email.xml
  app/src/main/res/layout/activity_pw_reset.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_sign_up2.xml
Labels: fix, Pull Request👊, 진/서진☀️

#471 [fix] : 타임피커 띄어쓰기 삭제
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewTimepicker.kt
Labels: fix, 리유/유리⛄

#472 [fix/#462]자동로그인
  app/src/main/java/com/umc/yourweather/di/UserSharedPreferences.kt
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt
  app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/Nickname.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
Labels: fix, Pull Request👊, 진/서진☀️

#479 [fix/#475] : 캘린더 상세보기 편집/저장 버튼 18dp
  app/src/main/res/layout/activity_calendar_modify_weather.xml
  app/src/main/res/layout/activity_calendar_plus_weather.xml
  app/src/main/res/layout/activity_calendar_weather_detail.xml
Labels: fix, Pull Request👊, 리유/유리⛄

#480 [fix/#477]뷰 수정
  app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt
  app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
  app/src/main/res/drawable/ic_calendardetailview_temp_orange.xml
  app/src/main/res/drawable/ic_calendardetailview_temp_orange_2.xml
  app/src/main/res/layout/activity_my_info.xml
  app/src/main/res/layout/item_calendar_detail_memolist.xml
Labels: add, feat, fix, Pull Request👊, 진/서진☀️

#481 [fix/#473] : 마이페이지 API를 붙여서 닉네임 변경 시 바뀐 닉네임이 바로 보이도록 수정
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloud.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloudWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRain.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRainWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSunWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunder.kt
  app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunderWeekly.kt
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageMyInfo.kt
Labels: fix, Pull Request👊, 리유/유리⛄

#483 [refactor/#482] home / 광고 뷰 랜덤 솔루션 추가
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragment.kt
  app/src/main/java/com/umc/yourweather/util/AdTextUtils.kt
  app/src/main/res/layout/fragment_home.xml
Labels: refactor, Pull Request👊, 카야/예린☁️

#487 [refactor/#486] weatherinput / 수정
  app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt
  app/src/main/res/layout/fragment_home_weather_input.xml
Labels: refactor, Pull Request👊, 카야/예린☁️

#488 [fix] : 닉네임 빈 경우 힌트로 닉네임 변경
  app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageNicknameChange.kt
Labels: fix, Pull Request👊, 리유/유리⛄

#490 [fix/#489] home / 레이아웃 수정
  app/src/main/res/layout/fragment_home.xml
Labels: fix, Pull Request👊, 카야/예린☁️
